In [ ]:
import numpy as np
import pandas as pd
import matplotlib
train = pd.read_csv("/work/Data/task3/train.csv")
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df_1 = train
del df_1['Name']
del df_1 ['Sex']
del df_1 ['Ticket']
del df_1 ['Cabin']
del df_1 ['Embarked']
df_1

     PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1         0       3  22.0      1      0   7.2500
1              2         1       1  38.0      1      0  71.2833
2              3         1       3  26.0      0      0   7.9250
3              4         1       1  35.0      1      0  53.1000
4              5         0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
886          887         0       2  27.0      0      0  13.0000
887          888         1       1  19.0      0      0  30.0000
888          889         0       3   NaN      1      2  23.4500
889          890         1       1  26.0      0      0  30.0000
890          891         0       3  32.0      0      0   7.7500

[891 rows x 7 columns]

In [ ]:
df_1 = df_1.dropna ()
df_1

     PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1         0       3  22.0      1      0   7.2500
1              2         1       1  38.0      1      0  71.2833
2              3         1       3  26.0      0      0   7.9250
3              4         1       1  35.0      1      0  53.1000
4              5         0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
885          886         0       3  39.0      0      5  29.1250
886          887         0       2  27.0      0      0  13.0000
887          888         1       1  19.0      0      0  30.0000
889          890         1       1  26.0      0      0  30.0000
890          891         0       3  32.0      0      0   7.7500

[714 rows x 7 columns]

In [ ]:
X = df_1.loc[:,df_1.columns!="Survived"]
y = df_1['Survived']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
model_1 = LinearRegression()
model_1.fit (X_train,y_train)
y_pred = model_1.predict (X_test)

In [ ]:
np.square(np.subtract(y_test,y_pred)).mean()

0.20095837252306603

In [ ]:
train_2 = pd.read_csv("/work/Data/task3/train_2.csv")
train_2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df_2 = train_2
df_2.drop(['Name','PassengerId','Ticket','Cabin','Embarked'], axis=1, inplace=True)
df_2 = df_2.dropna()
df_2

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0           0       3    male  22.0      1      0   7.2500
1           1       1  female  38.0      1      0  71.2833
2           1       3  female  26.0      0      0   7.9250
3           1       1  female  35.0      1      0  53.1000
4           0       3    male  35.0      0      0   8.0500
..        ...     ...     ...   ...    ...    ...      ...
885         0       3  female  39.0      0      5  29.1250
886         0       2    male  27.0      0      0  13.0000
887         1       1  female  19.0      0      0  30.0000
889         1       1    male  26.0      0      0  30.0000
890         0       3    male  32.0      0      0   7.7500

[714 rows x 7 columns]

Мужчины и женщины по-разному переносят холод и могут держаться на воде. Класс нужен для того, чтобы понять кого спасали впервую очередь. Сайблингс он борд нужен, ибо ты же пойдешь спасать своих родственников скорее всего и вохможно умрешь из-за этого

In [ ]:
from sklearn.preprocessing import LabelEncoder
df_2['Sex'] = LabelEncoder().fit_transform(df_2['Sex'])

/tmp/ipykernel_37/511053793.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['Sex'] = LabelEncoder().fit_transform(df_2['Sex'])

In [ ]:
df_2

     Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0           0       3    1  22.0      1      0   7.2500
1           1       1    0  38.0      1      0  71.2833
2           1       3    0  26.0      0      0   7.9250
3           1       1    0  35.0      1      0  53.1000
4           0       3    1  35.0      0      0   8.0500
..        ...     ...  ...   ...    ...    ...      ...
885         0       3    0  39.0      0      5  29.1250
886         0       2    1  27.0      0      0  13.0000
887         1       1    0  19.0      0      0  30.0000
889         1       1    1  26.0      0      0  30.0000
890         0       3    1  32.0      0      0   7.7500

[714 rows x 7 columns]

In [ ]:
corr = df_2.corr()
corr.style.background_gradient(cmap='coolwarm')

In [ ]:
X = df_2.loc[:,df_2.columns!="Survived"]
y = df_2['Survived']
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
model_2 = LinearRegression()
model_2.fit (X_train,y_train)
y_pred = model_2.predict (X_test)
print(mean_squared_error(y_test,y_pred))

0.16610617226902297

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=0cb3743c-bb9c-4ba1-a2f5-2218a7704d0c' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>